### ISSUE TITLE
Data download returns 404 for low_frequency_variant_observation and lq_clonal_variant_observation

### ISSUE THREAD

**Issue by priesgo** [TRON-Bioinformatics/covigator#100]

**Comment by johausmann** [comment]
I get the same error for the following additional files

* sample_covid19_portal.csv.gz
* variant_observation_covid19portal.csv.gz
* README
* variant_covid19portal.csv.gz
* subclonal_variant.csv.gz
* precomputed_ns_s_counts.csv.gz
* low_frequency_variant.csv.gz
* precomputed_variants_per_lineage.csv.gz
* last_update.csv.gz
* domain.csv.gz
* lq_clonal_variant.csv.gz

**Comment by johausmann** [comment]
Issue fixed

**Comment by johausmann** [comment]
The problem was caused by an outdated web server configuration that pointed to an old download location. We need to take this into account for future data updates.

**Comment by tungwinxp** [comment]
Hi I'm having the same issue and would like to download some of these raw complete table files. Do you have them available so I can look at iSNVs unfiltered per sample?
