### ISSUE TITLE
Update ENA accessor to include Nanopore data

### ISSUE THREAD

**Issue by johausmann** [TRON-Bioinformatics/covigator#104]
The accessor queries the ENA REST API and stores each sample metadata (ie: URLs to FASTQs, country, collection date, etc.). It also, optionally, downloads the FASTQ files and stores them in the file structure where they can be later found.

* The accessor needs to stop excluding nanopore samples when querying the REST API (instrument_platform)
* The accessor needs to know the library strategies used for Nanopore sequencing (Amplicon,...)

**Comment by priesgo** [comment]
I was looking into this old analysis https://github.com/TRON-Bioinformatics/covigator-analysis/blob/main/jupyter/01_ena_api_usage/ena_download.ipynb

I think you may want to look into the field `instrument_platform` rather than `library_strategy`

**Comment by johausmann** [comment]
That is right, but the accessor restricts the library strategies for the Illumina samples and filters them accordingly. Do we plan to do something similar for the Nanopore samples or do we include them all?

**Comment by priesgo** [comment]
As discussed this is maybe a question for Paul

**Comment by priesgo** [comment]
This is not in the roadmap anymore
