### ISSUE TITLE
ENA API update

### ISSUE THREAD

**Issue by johausmann** [TRON-Bioinformatics/covigator#112]
The ENA API was updated in May 2023. We need to check if the changes affect the CoVigator accessor module. 

 More information here:
 https://docs.google.com/document/d/1RPHmK8Pvm9UxSa21Ej3MkGoGYO9baSxwxk_dOuWWyNE/edit#heading=h.jq87g3izg5xr

**Comment by priesgo** [comment]
Just ran the ENA accessor on Ebola virus and there is a new field `tax_id` returned in the payload that crashes the accessor when the database object is created as follows `SampleEna(**run)`. As a quick fix I removed the field `tax_id` from the payload before creating the object, this works, but there may be better solutions. This may be connected with a potential need to support multiple viruses in the DB as `tax_id` would be precisely the discriminant. In the case of Ebolavirus I created a whole new set of tables using the `database_prefix`.

**Comment by johausmann** [comment]
Closed with #128
