### ISSUE TITLE
Host_tax_id field is NA for all queried ENA runs

### ISSUE THREAD

**Issue by johausmann** [TRON-Bioinformatics/covigator#130]
During the data update I noticed a serious problem in the ENA accessor. All samples were filtered out because of the missing host_tax_id, even though this is a field that is requested in the URL. It seems that this field is always NA no matter what samples we query. I also did a quick check with some Sars-Cov2 ENA runs that were already processed in a previous database update. Here we can observe the same problem.

* Example using existing run in database
https://www.ebi.ac.uk/ena/portal/api/search?result=read_run&format=tsv&query=%22run_accession=SRR21853160%22&fields=host_tax_id,host_scientific_name 

![image](https://github.com/TRON-Bioinformatics/covigator/assets/35309108/6eb512bc-06f7-419e-92f0-a7f7d4382272)

* Another example from the database

https://www.ebi.ac.uk/ena/portal/api/search?result=read_run&format=tsv&query=%22run_accession=DRR287659%22&fields=host_tax_id,host_scientific_name 

However, the host_scientific_name field is returned. We could update the accessor module to filter by either host_tx_id or host_scientific_name.

**Comment by johausmann** [comment]
For the new data release, we skip the host_tax_id check and check the host_scientific_name. Here we will accept the values Homo Sapiens and NA, since we assume that a large part of the NA samples come from human donors.

**Comment by priesgo** [comment]
Fixed by ENA upstream
