### ISSUE TITLE
Capture feedback from the dashboard

### ISSUE THREAD

**Issue by priesgo** [TRON-Bioinformatics/covigator#74]
We tried in the past to capture user feedback by providing buttons to create GitHub issues in the acknowledgments section. We did not receive anything so far. Either because not being published we have not reached a lot of people or because this is kind of hidden. 

It may be helpful to have a more pervasive provide feedback feature with a visible button available from all locations of the dashboard. The article below provides a description of how to do this in a Dash dashboard.
https://medium.com/codex/how-to-create-a-dashboard-with-a-contact-form-using-python-and-dash-ee3aacffd349

**Comment by johausmann** [comment]
As we need to send this feedback as some sort of email, these libraries/websites might be helpful
* https://github.com/kootenpv/yagmail
* https://github.com/mailgun/flanker
* https://realpython.com/python-send-email/
